# Generated by Django 6.0.6 on 2026-06-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
